### ISSUE TITLE
categorical features in multivariate time series

### ISSUE THREAD

**Issue by Sandy4321** [nkafr/temporal-fusion-transformer#1]
you mentioned in blog : categorical features are possible to use
but  it is not clear from your code
may you share example for forecasting multivariate time series   with mixture of categorical and continues features ?

**Comment by nkafr** [comment]
Hello! My example contains a categorical variable, and specifically the **consumer_id** feature - which essentially represents the unique ID of a time-series.

When I create the **TimeSeriesDataSet** object, I pass the argument: 

_static_categoricals=["consumer_id"]_

which is exacly the argument for defining a static categorical variable.
